baseurl = "/"
languageCode = "en-us"
title = "BNU-Statistics with R"
theme = "hugo-lithium"
googleAnalytics = "UA-179273490-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/" #where it is located
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/Roberto-Supe"


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    #highlightjsVersion = "9.12.0"
    #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "foundation"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    #MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

